### PR TITLE
added reply-to functionality for quoting

### PR DESCRIPTION
**Pull request by jlsajfj**
image
leo wants it

### CODE REVIEW

**Review by zaydtahir — CHANGES_REQUESTED** [review]
Should error if they do more than 2 arguments as well. Other than that it looks fine. I would be okay with merging as long as it's been tested.

**Comment by jlsajfj** [comment]
changed

**Review by zaydtahir — APPROVED** [review]
Looks good. Don't merge before testing.

**Review by zaydtahir — CHANGES_REQUESTED** [review]
My bad, can you change help to reflect these changes too?

**Review by jlsajfj — COMMENTED** [review]
this one is the change for help message

**Comment by jlsajfj** [comment]
shifted to main repo, opening pull from there

**Pull request closed without merging**
