### PR TITLE
added functionality to check if delete actually deleted anything

### PR DESCRIPTION
**Pull request by jlsajfj**
Refer to documentation [here](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.delete_one).

**TLDR:** delete_one returns an object that can check how many elements were actually deleted.

### CODE REVIEW

**Comment by jlsajfj** [comment]
Oops didnt link it

**Comment by jlsajfj** [comment]
#255

**Comment by sahil-kale** [comment]
@zaydtahir please review

**Review by zaydtahir — APPROVED** [review]
Nice work, looks good

**Pull request merged**
